### ISSUE TITLE
option for more than gaming platforms, like anime/tv show tracking platforms 

### ISSUE THREAD

**Issue by Beastmastah64** [stroupbslayen/GamerDB#3]
Discord is a place where lot of people talking about anime and TV shows,
would be great if there is an option to add usernames for top tracking sites like 

- Anilist - https://anilist.co (Anime Tracking)
- TV Time - https://www.tvtime.com/  (TV shows and Anime Tracking)
in these sites, people can become friends and follow each other profiles and updates

**Comment by CasuallyCalm** [comment]
I'm always open to adding more platforms that are suggested in the support server. https://discord.gg/CWNAg6N
